export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_CURRENCIES_FAILURE = 'FETCH_CURRENCIES_FAILURE';

export const FETCH_PRICE_SUCCESS = 'FETCH_PRICE_SUCCESS';
export const FETCH_PRICE_FAILURE = 'FETCH_PRICE_FAILURE';

export const START_API_CALL = 'START_API_CALL';
export const END_API_CALL = 'END_API_CALL';

export const SELECT_CURRENCY_FROM = 'SELECT_CURRENCY_FROM';
export const SELECT_CURRENCY_TO = 'SELECT_CURRENCY_TO';